version: 2
jobs:
  build_package:
    docker:
      - image: giorgosdi/asm-0.2.5:latest
    steps:
      - checkout

      - run:
          name: create pip package
          command: |
            . venv/bin/activate
            python3 setup.py sdist bdist_wheel
            twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u ${USERNAME} -p ${PASSWORD}
  run_tests:
    docker:
      - image: giorgosdi/asm-0.2.5:latest
    steps:
      - checkout

      - run:
          name: run tests
          command: |
            py.test
workflows:
  version: 2
  main:
    jobs:
      - run_tests
      - build_package:
          requires:
            - run_tests
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
  test:
    jobs:
      - run_tests
