version: 2
jobs:
  build_package:
    docker:
      - image: giorgosdi/asm-0.2.5:latest
    steps:
      - checkout

      - run:
          name: create pip package
          command: |
            python3 setup.py sdist bdist_wheel
            twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u ${USERNAME} -p ${PASSWORD}
  run_tests:
    docker:
      - image: giorgosdi/pytest3
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            pip install -r requirements.txt
      - run:
          name: Create assume directory (TEMP STEP)
          command: |
            mkdir /root/.assume
      - run:
          name: run tests
          command: |
            pytest

workflows:
  version: 2
  main:
    jobs:
      - run_tests
      - build_package:
          requires:
            - run_tests
          filters:
            tags:
              only: 
                - /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: 
                - /.*/
  test:
    jobs:
      - run_tests
