version: 2
jobs:
  environment_variables:
    docker:
      - image: alpine
  steps:
    - checkout
    - run:
        name: Set environment variables
        command: |
          echo 'export TAG=$(cat setup.py | grep "version" | cut -d "=" -f 2 | cut -d "'" -f 2 | cut -d "'" -f 1)' >> $BASH_ENV
  build_image:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run:
          name: Build container image
          command: |
            echo ${TAG}
            echo ${CIRCLE_BRANCH}
            # docker image build -t giorgosdi/asm:${TAG}-${CIRCLE_BRANCH}


  build_package:
    docker:
      - image: giorgosdi/asm-0.2.5:latest
    steps:
      - checkout

      - run:
          name: create pip package
          command: |
            python3 setup.py sdist bdist_wheel
            twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u ${USERNAME} -p ${PASSWORD}
  run_tests:
    docker:
      - image: giorgosdi/asm-0.2.5:latest
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            py.test
workflows:
  version: 2
  main:
    jobs:
      - run_tests
      - build_package:
          requires:
            - run_tests
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
  test:
    jobs:
      - run_tests
  build_image:
    jobs:
      - environment_variables
      - build_image:
          requires:
            - environment_variables
